export const MONGO_DB_URI = 'MONGO_DB_URI';
export const MONGODB = 'mongodb';

export const SESSION_SECRET = 'SESSION_SECRET';
export const SESSION_COOKIE_MAX_AGE = 'SESSION_COOKIE_MAX_AGE';

export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN';
export const JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN';

export const FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID';
export const FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET';
export const FACEBOOK_REDIRECT_URL = 'FACEBOOK_REDIRECT_URL';

export const MYSTIFLY_TARGET = 'MYSTIFLY_TARGET';
export const MYSTIFLY_BASE_URL = 'MYSTIFLY_BASE_URL';
export const MYSTIFLY_AUTH_BEARER = 'MYSTIFLY_AUTH_BEARER';
export const MYSTIFLY_REQUEST_OPTIONS = 'MYSTIFLY_REQUEST_OPTIONS';

export const TBO_BASE_URL = 'TBO_BASE_URL';
export const TBO_AUTH_USERNAME = 'TBO_AUTH_USERNAME';
export const TBO_AUTH_PASSWORD = 'TBO_AUTH_PASSWORD';

export const AMADEUS_CLIENT_ID = 'AMADEUS_CLIENT_ID';
export const AMADEUS_CLIENT_SECRET = 'AMADEUS_CLIENT_SECRET';

export const TRIPNINJA_BASE_URL = 'TRIPNINJA_BASE_URL';
export const TRIPNINJA_AUTH_USERNAME = 'TRIPNINJA_AUTH_USERNAME';
export const TRIPNINJA_AUTH_PASSWORD = 'TRIPNINJA_AUTH_PASSWORD';

export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_TTL = 'REDIS_TTL';

export const HTTP_MYSTIFLY_FLIGHTS_TIMEOUT = 'HTTP_MYSTIFLY_FLIGHTS_TIMEOUT';
export const HTTP_TBO_HOTELS_TIMEOUT = 'HTTP_TBO_HOTELS_TIMEOUT';

export const PAYMONGO_BASE_URL = 'PAYMONGO_BASE_URL';
export const PAYMONGO_AUTHORIZATION = 'PAYMONGO_AUTHORIZATION';
export const PAYMONGO_REDIRECT_BASE_URL = 'PAYMONGO_REDIRECT_BASE_URL';

export const POSTGRES = 'postgres';
export const POSTGRES_HOST = 'POSTGRES_HOST';
export const POSTGRES_PORT = 'POSTGRES_PORT';
export const POSTGRES_USERNAME = 'POSTGRES_USERNAME';
export const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD';
export const POSTGRES_DATABASE = 'POSTGRES_DATABASE';
export const POSTGRES_SYNCHRONIZE = 'POSTGRES_SYNCHRONIZE';
export const POSTGRES_SSL = 'POSTGRES_SSL';
export const POSTGRES_EXTRA = 'POSTGRES_EXTRA';

export const TYPEORM_OPTIONS = 'TYPEORM_OPTIONS';
export const TYPEORM_MONGO_DB_OPTIONS = 'TYPEORM_MONGO_DB_OPTIONS';
export const TYPEORM_MONGODB = 'TYPEORM_MONGODB';

export const MAILER_USER = 'MAILER_USER';
export const MAILER_PASS = 'MAILER_PASS';
export const MAILER_HOST = 'MAILER_HOST';

export const CREDENTIALS_IV = 'CREDENTIALS_IV';
export const CREDENTIALS_PASSWORD = 'CREDENTIALS_PASSWORD';
export const CREDENTIALS_SALT = 'CREDENTIALS_SALT';

export const ANALYTICS_FLIGHTS_SEARCH = 'ANALYTICS_FLIGHTS_SEARCH';
